package session

import (
	"encoding/json"
	"errors"
	"sync"
	"testing"
	"time"

	"github.com/Luo-root/pulse/llm"
)

// TestCreateNormalizesHeader：空 ID 生成、CreatedAt 填充、FormatVersion
// 填充；不兼容版本拒绝加载。
func TestCreateNormalizesHeader(t *testing.T) {
	store := NewMemoryStore()
	sess, err := store.Create(t.Context(), SessionHeader{})
	if err != nil {
		t.Fatal(err)
	}
	hdr := sess.Header()
	if hdr.SessionID == "" {
		t.Fatal("empty SessionID must be generated by store")
	}
	if hdr.CreatedAt.IsZero() {
		t.Fatal("zero CreatedAt must be filled by store")
	}
	if hdr.FormatVersion != FormatVersion {
		t.Fatalf("FormatVersion = %d, want %d", hdr.FormatVersion, FormatVersion)
	}
	_, err = store.Create(t.Context(), SessionHeader{FormatVersion: FormatVersion + 1})
	if !errors.Is(err, ErrFormatVersion) {
		t.Fatalf("err = %v, want ErrFormatVersion", err)
	}
}

// TestCreateRejectsSecondWriter：同 ID 已存在拒绝；并发 Create 同一 ID
// 恰好一个成功（内存单写者的确定性形态）。
func TestCreateRejectsSecondWriter(t *testing.T) {
	store := NewMemoryStore()
	if _, err := store.Create(t.Context(), SessionHeader{SessionID: "dup"}); err != nil {
		t.Fatal(err)
	}
	if _, err := store.Create(t.Context(), SessionHeader{SessionID: "dup"}); !errors.Is(err, ErrSessionExists) {
		t.Fatalf("err = %v, want ErrSessionExists", err)
	}
	const n = 8
	var wg sync.WaitGroup
	results := make([]error, n)
	for i := 0; i < n; i++ {
		wg.Add(1)
		go func(i int) {
			defer wg.Done()
			_, results[i] = store.Create(t.Context(), SessionHeader{SessionID: "race"})
		}(i)
	}
	wg.Wait()
	ok := 0
	for _, err := range results {
		if err == nil {
			ok++
		} else if !errors.Is(err, ErrSessionExists) {
			t.Fatalf("unexpected error: %v", err)
		}
	}
	if ok != 1 {
		t.Fatalf("exactly one creator must win; got %d", ok)
	}
}

// TestOpenColdRecoverUnpaired：assistant 的 ToolCall 无 result → Open 补
// IsError result 且真实写回 log（Events 可查、Surface 合法）。
func TestOpenColdRecoverUnpaired(t *testing.T) {
	store := NewMemoryStore()
	sess, err := store.Create(t.Context(), SessionHeader{})
	if err != nil {
		t.Fatal(err)
	}
	id := sess.Header().SessionID
	ctx := t.Context()
	// 模拟崩溃现场：call 已记，result 未记。
	if _, err := sess.Append(ctx, assistantDraft(t, llm.Call(llm.ToolCall{ID: "c1"}))); err != nil {
		t.Fatal(err)
	}
	before, _ := sess.Events(ctx, 0)

	reopened, err := store.Open(ctx, id)
	if err != nil {
		t.Fatal(err)
	}
	events, err := reopened.Events(ctx, 0)
	if err != nil {
		t.Fatal(err)
	}
	if len(events) != len(before)+1 {
		t.Fatalf("events = %d, want %d（合成事件必须真实 Append 写回 log）", len(events), len(before)+1)
	}
	last := events[len(events)-1]
	if last.Type != EventToolResult {
		t.Fatalf("synthetic type = %s, want tool.result", last.Type)
	}
	var p ToolResultPayload
	if err := json.Unmarshal(last.Data, &p); err != nil || p.ToolCallID != "c1" || !p.IsError {
		t.Fatalf("synthetic payload = %+v (err=%v), want c1/IsError", p, err)
	}
	surface, err := reopened.Surface(ctx)
	if err != nil {
		t.Fatal(err)
	}
	// surface：assistant(带 call) + tool(interrupted)。
	if len(surface) != 2 || surface[1].Role != llm.RoleTool {
		t.Fatalf("surface = %v", surface)
	}
	res := surface[1].Parts[0].ToolResultValue
	if res == nil || res.ToolCallID != "c1" || !res.IsError || res.Content[0].Text != interruptedResultText {
		t.Fatalf("synthetic result = %+v", res)
	}
}

// TestOpenColdRecoverOpenTurnStep：未闭合 step/turn 按嵌套顺序补
// interrupted 结束事件（step 先于 turn）。
func TestOpenColdRecoverOpenTurnStep(t *testing.T) {
	store := NewMemoryStore()
	sess, err := store.Create(t.Context(), SessionHeader{})
	if err != nil {
		t.Fatal(err)
	}
	ctx := t.Context()
	for _, d := range []EventDraft{
		lifecycleDraft(t, EventTurnStarted, "t1", ""),
		lifecycleDraft(t, EventStepStarted, "s1", ""),
	} {
		if _, err := sess.Append(ctx, d); err != nil {
			t.Fatal(err)
		}
	}
	reopened, err := store.Open(ctx, sess.Header().SessionID)
	if err != nil {
		t.Fatal(err)
	}
	events, _ := reopened.Events(ctx, 0)
	if len(events) != 4 {
		t.Fatalf("events = %d, want 4", len(events))
	}
	if events[2].Type != EventStepEnded || events[3].Type != EventTurnEnded {
		t.Fatalf("synthetic order = %s, %s; want step.ended then turn.ended", events[2].Type, events[3].Type)
	}
	var stepEnded, turnEnded LifecyclePayload
	if err := json.Unmarshal(events[2].Data, &stepEnded); err != nil || stepEnded.Reason != ReasonInterrupted {
		t.Fatalf("step.ended = %+v (err=%v), want interrupted", stepEnded, err)
	}
	if stepEnded.ID != "s1" {
		t.Fatalf("step.ended.ID = %q, want %q（合成 ended 必须回带 started 的 ID）", stepEnded.ID, "s1")
	}
	if err := json.Unmarshal(events[3].Data, &turnEnded); err != nil || turnEnded.Reason != ReasonInterrupted {
		t.Fatalf("turn.ended = %+v (err=%v), want interrupted", turnEnded, err)
	}
	if turnEnded.ID != "t1" {
		t.Fatalf("turn.ended.ID = %q, want %q", turnEnded.ID, "t1")
	}
}

// TestLiveSessionNotRepaired：live 会话（Create 后持有、不经 Open）不做
// 冷补——Surface 折出 unpaired 现场，日志不变。
func TestLiveSessionNotRepaired(t *testing.T) {
	sess := newTestSession(t)
	ctx := t.Context()
	if _, err := sess.Append(ctx, assistantDraft(t, llm.Call(llm.ToolCall{ID: "c1"}))); err != nil {
		t.Fatal(err)
	}
	surface, err := sess.Surface(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if len(surface) != 1 || surface[0].Role != llm.RoleAssistant {
		t.Fatalf("live surface = %v; 修复只能发生在 Open 冷恢复", surface)
	}
	events, _ := sess.Events(ctx, 0)
	if len(events) != 1 {
		t.Fatalf("live events = %d, want 1（不自动补写）", len(events))
	}
}

// TestOpenIdempotentAfterRecover：恢复完成后重复 Open 不再补写。
func TestOpenIdempotentAfterRecover(t *testing.T) {
	store := NewMemoryStore()
	sess, _ := store.Create(t.Context(), SessionHeader{})
	ctx := t.Context()
	_, _ = sess.Append(ctx, assistantDraft(t, llm.Call(llm.ToolCall{ID: "c1"})))
	if _, err := store.Open(ctx, sess.Header().SessionID); err != nil {
		t.Fatal(err)
	}
	first, _ := sess.Events(ctx, 0)
	if _, err := store.Open(ctx, sess.Header().SessionID); err != nil {
		t.Fatal(err)
	}
	second, _ := sess.Events(ctx, 0)
	if len(first) != len(second) {
		t.Fatalf("events grew on second open: %d → %d", len(first), len(second))
	}
}

// TestOpenRejectsUnknownRequired：恢复扫描遇到未知 required 事件 → 拒绝
// Open（fail closed）。直接构造白盒现场（Append 已在写入端拦截该情况）。
func TestOpenRejectsUnknownRequired(t *testing.T) {
	store := NewMemoryStore()
	sess, _ := store.Create(t.Context(), SessionHeader{})
	ms := sess.(*memSession)
	ms.events = append(ms.events, EventEnvelope{
		Seq: 1, Time: time.Now(), Type: EventType("plugin/x/unknown"), Ignorable: false,
	})
	ms.seq = 1
	if _, err := store.Open(t.Context(), ms.hdr.SessionID); !errors.Is(err, ErrUnknownRequired) {
		t.Fatalf("err = %v, want ErrUnknownRequired", err)
	}
}

// TestConcurrentOpenSingleWriter：并发 Open 同一半截现场，恰好恢复一次；
// 第二写者得到 ErrWriterBusy（或等待窗口过后看到已闭合状态，幂等返回）。
// 两种结果都合法，但合成事件必须恰好一份。
func TestConcurrentOpenSingleWriter(t *testing.T) {
	store := NewMemoryStore()
	sess, _ := store.Create(t.Context(), SessionHeader{})
	ctx := t.Context()
	_, _ = sess.Append(ctx, assistantDraft(t, llm.Call(llm.ToolCall{ID: "c1"})))
	id := sess.Header().SessionID

	const n = 8
	var wg sync.WaitGroup
	errs := make([]error, n)
	for i := 0; i < n; i++ {
		wg.Add(1)
		go func(i int) {
			defer wg.Done()
			_, errs[i] = store.Open(ctx, id)
		}(i)
	}
	wg.Wait()

	events, _ := sess.Events(ctx, 0)
	synthetic := 0
	for _, ev := range events {
		if ev.Type == EventToolResult {
			synthetic++
		}
	}
	if synthetic != 1 {
		t.Fatalf("synthetic tool.result = %d, want exactly 1; events=%d", synthetic, len(events))
	}
	for i, err := range errs {
		if err != nil && !errors.Is(err, ErrWriterBusy) {
			t.Fatalf("goroutine %d: unexpected error %v", i, err)
		}
	}
}

// TestListCursorPagination：CreatedAt 降序 + SessionID tiebreak；游标翻页
// 不重不漏；游标失效从头（安全行为）。
func TestListCursorPagination(t *testing.T) {
	store := NewMemoryStore(WithListPageSize(2))
	base := time.Now()
	ids := []string{"b", "a", "d", "c", "e"}
	for i, id := range ids {
		// 同一 CreatedAt 制造 tiebreak 场景。
		at := base.Add(time.Duration(i/2) * time.Minute)
		if _, err := store.Create(t.Context(), SessionHeader{SessionID: id, CreatedAt: at}); err != nil {
			t.Fatal(err)
		}
	}
	// 期望顺序：CreatedAt 降序，同刻 SessionID 升序（tiebreak）。
	// 2 分钟：e；1 分钟：c, d；0 分钟：a, b。
	want := []string{"e", "c", "d", "a", "b"}
	var got []string
	next := ""
	for page := 0; ; page++ {
		headers, n, err := store.List(t.Context(), SessionFilter{After: next})
		if err != nil {
			t.Fatal(err)
		}
		if len(headers) == 0 {
			break
		}
		for _, h := range headers {
			got = append(got, h.SessionID)
		}
		if n == "" {
			break
		}
		if page > 10 {
			t.Fatal("pagination did not terminate")
		}
		next = n
	}
	if len(got) != len(want) {
		t.Fatalf("listed %v, want %v", got, want)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Fatalf("listed %v, want %v（CreatedAt 降序 + SessionID tiebreak）", got, want)
		}
	}
	// 游标失效 → ErrCursorStale（静默从头会重复返回，不做）。
	headers, _, err := store.List(t.Context(), SessionFilter{After: "gone"})
	if !errors.Is(err, ErrCursorStale) || headers != nil {
		t.Fatalf("stale cursor: err=%v, headers=%d; want ErrCursorStale", err, len(headers))
	}
}

// TestHeaderSnapshotIsolation：Header() 返回快照，后续 Append 不改写已
// 取出的 header。
func TestHeaderSnapshotIsolation(t *testing.T) {
	sess := newTestSession(t)
	h1 := sess.Header()
	_, _ = sess.Append(t.Context(), userDraft(t, "x"))
	h2 := sess.Header()
	if h1.CreatedAt != h2.CreatedAt || h1.SessionID != h2.SessionID {
		t.Fatal("header mutated")
	}
}

// TestChunkOnlyCrashKeepsLastLegal：只有 assistant.chunk、无 message.assistant
// 的崩溃现场（§9.3 表第二行）——chunk 永不进 surface，Surface 停在上一
// 合法消息；冷恢复不为 chunk 合成任何事件（chunk 无需闭合）。
func TestChunkOnlyCrashKeepsLastLegal(t *testing.T) {
	store := NewMemoryStore()
	sess, _ := store.Create(t.Context(), SessionHeader{})
	ctx := t.Context()
	if _, err := sess.Append(ctx, userDraft(t, "q1")); err != nil {
		t.Fatal(err)
	}
	if _, err := sess.Append(ctx, assistantDraft(t, llm.Text("a1"))); err != nil {
		t.Fatal(err)
	}
	if _, err := sess.Append(ctx, EventDraft{Type: EventAssistantChunk, Data: mustJSONPayload(t, ChunkPayload{Text: "half answer"})}); err != nil {
		t.Fatal(err)
	}
	// live：Surface 停在上一合法消息，不出现半截 assistant。
	surface, err := sess.Surface(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if len(surface) != 2 || surface[1].Text() != "a1" {
		t.Fatalf("live surface = %v, want [user, assistant(a1)]", surface)
	}
	// 冷恢复：chunk 不触发合成事件，日志不变。
	reopened, err := store.Open(ctx, sess.Header().SessionID)
	if err != nil {
		t.Fatal(err)
	}
	events, _ := reopened.Events(ctx, 0)
	if len(events) != 3 {
		t.Fatalf("events = %d, want 3（chunk 无需闭合，不合成）", len(events))
	}
	surface2, err := reopened.Surface(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if len(surface2) != 2 || surface2[1].Text() != "a1" {
		t.Fatalf("recovered surface = %v, want [user, assistant(a1)]", surface2)
	}
}

// TestOpenAndAppendMutuallyExclusive：Open 冷恢复与 Append 同锁互斥——
// 并发下 Seq 严格连续，合成 turn.ended 恰好一份（不因并发重复补写）。
func TestOpenAndAppendMutuallyExclusive(t *testing.T) {
	store := NewMemoryStore()
	sess, _ := store.Create(t.Context(), SessionHeader{})
	ctx := t.Context()
	if _, err := sess.Append(ctx, lifecycleDraft(t, EventTurnStarted, "t1", "")); err != nil {
		t.Fatal(err)
	}
	id := sess.Header().SessionID

	var wg sync.WaitGroup
	for i := 0; i < 4; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			_, _ = store.Open(ctx, id) // 冷恢复写路径
		}()
	}
	for i := 0; i < 4; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			_, _ = sess.Append(ctx, userDraft(t, "x")) // 并发 Append
		}()
	}
	wg.Wait()

	events, _ := sess.Events(ctx, 0)
	endedCount := 0
	for i, ev := range events {
		if ev.Seq != uint64(i+1) {
			t.Fatalf("seq gap at %d: seq=%d（Open 与 Append 必须同锁串行）", i, ev.Seq)
		}
		if ev.Type == EventTurnEnded {
			endedCount++
		}
	}
	if endedCount != 1 {
		t.Fatalf("synthetic turn.ended = %d, want exactly 1", endedCount)
	}
}

// TestDeleteVsAppendRace：Delete 的 deleted 置位与 Append 的检查同锁——
// 并发下每个成功 Append 恰好落一条事件，被拒者零写入；「报错又写入」
// 的组合不存在。
func TestDeleteVsAppendRace(t *testing.T) {
	store := NewMemoryStore()
	sess, _ := store.Create(t.Context(), SessionHeader{})
	ctx := t.Context()
	id := sess.Header().SessionID

	var mu sync.Mutex
	appended := 0
	var wg sync.WaitGroup
	for i := 0; i < 4; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			_ = store.Delete(ctx, id)
		}()
	}
	for i := 0; i < 8; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			if _, err := sess.Append(ctx, userDraft(t, "x")); err == nil {
				mu.Lock()
				appended++
				mu.Unlock()
			}
		}()
	}
	wg.Wait()

	events, _ := sess.Events(ctx, 0)
	if len(events) != appended {
		t.Fatalf("events = %d, successful appends = %d（不允许报错又写入）", len(events), appended)
	}
	// Delete 完成后（wg 已收口）再 Append 必然失败。
	if _, err := sess.Append(ctx, userDraft(t, "late")); !errors.Is(err, ErrDeleted) {
		t.Fatalf("append after delete: %v, want ErrDeleted", err)
	}
	events, _ = sess.Events(ctx, 0)
	if len(events) != appended {
		t.Fatalf("post-delete append leaked: events = %d, want %d", len(events), appended)
	}
}
